
# This file is automatically generated, you probably don't want to edit this

MannKendallOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MannKendallOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL, ...) {

            super$initialize(
                package="TrendAnalysis",
                name="MannKendall",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)

            self$.addOption(private$..x)
        }),
    active = list(
        x = function() private$..x$value),
    private = list(
        ..x = NA)
)

MannKendallResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MannKendallResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="MannKendall test for trend analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="MannKendall test for trend analysis"))}))

MannKendallBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MannKendallBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "TrendAnalysis",
                name = "MannKendall",
                version = c(1,0,0),
                options = options,
                results = MannKendallResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' MannKendall test for trend analysis
#'
#' 
#' @param data the data as a data frame
#' @param x a vector of strings specifying the series variable in \code{data}
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
MannKendall <- function(
    data,
    x) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("MannKendall requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL))


    options <- MannKendallOptions$new(
        x = x)

    analysis <- MannKendallClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

